### ISSUE TITLE
Custom connections

### ISSUE THREAD

**Issue by jwoertink** [jGRUBBS/wordpress-rails#3]
It would be awesome to be able to set the `abstract_class` and `establish_connection` through an initializer? 

Maybe something like

```ruby
Wordpress.config do |c|
  c.connection = "wordpress_#{Rails.env}"
  c.abstract_class = Wordpress::Base
end
```

That way, your `database.yml` could be setup like

```yaml
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

wordpress_development:
  adapter: mysql2
  database: wp_blog
  host: localhost
  username: admin
  password: whatever
```
